<!DOCTYPE html>
<html>
<head>
    <title>0xDEADFA11 / {{ title }}</title>
    <link rel="stylesheet" href="/css/0xDEADFA11.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<header>
    <nav class="container">
        <ul>
            <li class="deadfa11">0xDEADFA11</li>
            <li><a href="/" title="Introduction nonsense and Open Sawrce">Home</a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/portfolio">Portfolio</a></li>
            <li><a href="/cv">CV/Resume</a></li>
            <li><a href="/cv">Contact</a></li>
            <!--li><input type="search" name="q" id="q" placeholder="Search"></li-->
            <li class="icon">
                <a href="https://twitter.com/nickpack"><i class="icon-twitter"></i></a>
                <a href="https://github.com/nickpack"><i class="icon-github"></i></a>
                <a href=""><i class="icon-linkedin-sign"></i></a>
                <a href=""><i class="icon-google-plus-sign"></i></a>
            </li>
        </ul>
    </nav>
</header>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<footer>
    <div class="container">
        <section class="four columns alpha">
            <h4>Whats here?</h4>
            <ul>
                <li class="alpha omega"><a href="/" title="Introduction nonsense and Open Sawrce">Home</a></li>
                <li class="alpha omega"><a href="/blog">Blog</a></li>
            </ul>
        </section>
        <section class="four columns">
            <h4>Social</h4>
            <ul>
                <li class="alpha omega"><a href="https://twitter.com/nickpack" title="@nickpack on Twitter">Twitter</a></li>
                <li class="alpha omega"><a href="https://github.com/nickpack" title="@nickpack on Github">Github</a></li>
                <li class="alpha omega"><a href="https://instagr.am/nickp666" title="@nickp666 on Instagram">Instagram</a></li>
            </ul>
        </section>
        <section class="four columns">
            <h4>Social</h4>
            <ul>
                <li class="alpha omega"><a href="https://twitter.com/nickpack" title="@nickpack on Twitter">Twitter</a></li>
                <li class="alpha omega"><a href="https://github.com/nickpack" title="@nickpack on Github">Github</a></li>
                <li class="alpha omega"><a href="https://instagr.am/nickp666" title="@nickp666 on Instagram">Instagram</a></li>
            </ul>
        </section>
        <section class="four columns omega">
            <h4>Built With</h4>
            <ul>
                <li class="alpha omega"><a href="http://nodejs.org">node</a></li>
                <li class="alpha omega"><a href="http://locomotivejs.org">Locomotive</a> / <a href="http://expressjs.org">express</a></li>
                <li class="alpha omega"><a href="https://github.com/nickpack" title="@nickpack on Github">Github</a></li>
                <li class="alpha omega"><a href="https://instagr.am/nickp666" title="@nickp666 on Instagram">Instagram</a></li>
            </ul>
        </section>
    </div>
    <p class="container">Copyright 2013 <a href="http://www.cohaesus.co.uk">Nikki James Pack.</a></p>
</footer>
<script type="text/javascript" src="/js/libs.min.js"></script>
<script type="text/javascript" src="/js/0xDEADFA11.min.js"></script>
</body>
</html>